language: dart

# Workaround for issue with sandboxed Chrome in containerized Travis builds.
sudo: required
addons:
  chrome: stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache
    - $HOME/.dart_tool

stages:
  - quality
  - test

jobs:
  include:
    - stage: quality
      dart: "2.0.0-dev.49.0"
      script:
        - pub run dart_dev analyze
        - pub run dependency_validator -i coverage

    - stage: test
      dart: "2.0.0-dev.49.0"
      script: ./tool/travis.sh test:unit dartdevc

    - stage: test
      dart: "2.0.0-dev.49.0"
      script: ./tool/travis.sh test:unit dart2js

    - stage: test
      dart: "2.0.0-dev.49.0"
      script: ./tool/travis.sh test:integration dartdevc

    - stage: test
      dart: "2.0.0-dev.49.0"
      script: ./tool/travis.sh test:integration dart2js

#    - stage: test
#      dart: "2.0.0-dev.49.0"
#      script:
#        - ./tool/generate_coverage.sh
#        - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
