# Site settings
title: OverReact
description: A framework for building statically-typed React UI components using Dart.
pkg_name: over_react
repo: https://github.com/Workiva/over_react/
latest_version: 1.0.0
gacode: "TODO"

# Directories
source:       .
destination:  ./_site
plugins_dir:  docs/_plugins
layouts_dir:  docs/_layouts
data_dir:     docs/_data
includes_dir: docs/_includes

exclude:
  - integrate
  - lib
  - test
  - tool
  - packages
  - docs/sass/bootstrap

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

sass:
  style: compressed
  sass_dir: docs/sass

# Serving
baseurl: ""
url: "TODO"
port: 8020
