builders:
  overReactBuilder:
    import: "package:over_react/src/builder/builder.dart"
    builder_factories: ["overReactBuilder"]
    build_extensions: {".dart" : [".overReactBuilder.info"]}
    auto_apply: none
    build_to: source

targets:
  $default:
    builders:
      built_value_generator|built_value:
        enabled: false
      over_react|overReactBuilder:
        enabled: true

