builders:
  overReactBuilder:
    import: "package:over_react/src/builder/builder.dart"
    builder_factories: ["overReactBuilder"]
    build_extensions: {".dart" : [".overReactBuilder.g.dart"]}
    auto_apply: none
    build_to: source

targets:
  $default:
    sources:
      include:
        - "example/builder/**"
      exclude:
        - ".dart_tool"
    builders:
      built_value_generator|built_value:
        enabled: false
      built_redux|built_redux:
        enabled: false
      over_react|overReactBuilder:
        enabled: true

